import path from "path";

/**
 * Helpers for turning request input into a filesystem path that is provably
 * contained inside a base directory.
 *
 * The previous code guarded these with
 *   targetPath.startsWith(path.join(base, id))
 * which has two problems:
 *   1. `path.join` normalises `..`, so a server id like `..` silently escapes
 *      the servers directory before the check even runs.
 *   2. String prefix matching is not path-segment aware, so a base of
 *      `.data/servers/abc` also "contains" `.data/servers/abcdef/...`.
 */

export const SERVERS_ROOT = path.join(process.cwd(), ".data", "servers");

/** Server ids are generated by the panel; treat anything else as hostile. */
const SERVER_ID = /^[A-Za-z0-9_-]{1,64}$/;

export const isValidServerId = (id: unknown): id is string =>
  typeof id === "string" && SERVER_ID.test(id);

/**
 * Resolve the absolute directory for a server.
 * Returns null when the id is not a plain identifier.
 */
export const getServerDir = (id: unknown): string | null => {
  if (!isValidServerId(id)) return null;
  return path.join(SERVERS_ROOT, id);
};

/**
 * Resolve `relative` inside `baseDir`, refusing anything that escapes it.
 *
 * Uses path.relative rather than string comparison so the result is
 * segment-accurate: both ".." escapes and sibling-prefix collisions are caught.
 */
export const resolveWithin = (baseDir: string, relative: unknown): string | null => {
  if (relative === undefined || relative === null) relative = "";
  if (typeof relative !== "string") return null;
  // Reject NUL bytes and absolute paths outright rather than relying on
  // normalisation to notice.
  if (relative.includes("\0")) return null;

  const resolvedBase = path.resolve(baseDir);
  const target = path.resolve(resolvedBase, relative);
  const rel = path.relative(resolvedBase, target);

  // rel === "" is the base itself, which is valid. Anything outside means rel is
  // either ".." or starts with "../" (a different root/drive gives an absolute
  // path). Compare whole segments: a plain startsWith("..") would also reject
  // legitimate names such as "...config" or "..foo".
  if (rel === "") return target;
  if (rel === ".." || rel.startsWith(".." + path.sep) || path.isAbsolute(rel)) return null;
  return target;
};

/**
 * True when `target` is inside `baseDir` (segment-aware).
 */
export const isInside = (baseDir: string, target: string): boolean =>
  resolveWithin(baseDir, path.relative(path.resolve(baseDir), path.resolve(target))) !== null;
